# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [2]:
# ejercicio 1
a=np.array([1,2,3,4])
np.where(a==0)

(array([], dtype=int64),)

In [3]:
# ejercicio 2
a=np.array([0,0,2,0])
np.where(a!=0)

(array([2]),)

In [4]:
# ejercicio 3
a=np.array([1,2,np.nan,np.inf])
np.where(np.isnan(a) | np.isinf(a)) # va a regresar las posiciones donde estan esos valores

(array([2, 3]),)

In [5]:
# ejercicio 4
a=np.array([1,2,np.inf])
np.where(np.isinf(a))

(array([2]),)

In [6]:
# ejercicio 5
a=np.array([1,np.nan,2])
np.where(np.isnan(a))

(array([1]),)

In [7]:
# ejercicio 6
a=np.array([1,np.nan,2])
np.where(np.isnan(a))

(array([1]),)

In [8]:
# ejercicio 7
a=np.array([1,3,5])
b=np.array([2,3,4])

print("a > b  :", a > b)
print("a >= b :", a >= b)
print("a < b  :", a < b)
print("a <= b :", a <= b)

a > b  : [False False  True]
a >= b : [False  True  True]
a < b  : [ True False False]
a <= b : [ True  True False]


In [ ]:
# ejercicio 8
ceros = np.zeros(10)
unos = np.ones(10)
cincos = np.full(10, 5)
print(ceros,unos,cincos)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5 5 5 5 5 5 5 5 5 5]


In [10]:
# ejercicio 9
a = np.arange(30, 71)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [12]:
# ejercicio 10
a = np.arange(30, 71, 2)
a

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [ ]:
# ejercicio 11
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# ejercicio 12
num = np.random.rand()
num

0.8863809729824841

In [16]:
# ejercicio 13
a = np.random.randn(15)
a

array([-0.42447327, -1.73850977,  0.75179965, -1.56925071,  0.62489204,
       -0.139799  , -1.4230621 ,  0.12538551, -0.52836847, -0.45610573,
       -0.84220455, -0.9899422 , -1.01355397, -0.61093653, -0.8852939 ])

In [ ]:
# ejercicio 14
a = np.arange(15, 56)
nuevo = a[1:-1]
print(nuevo)

In [19]:
# ejercicio 15
a = np.linspace(5, 50, 10)
a

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [20]:
# ejercicio 16
a = np.arange(21)
a[9:16] *= -1
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [ ]:
# ejercicio 17
a = np.array([1, 2, 3])
lista = a.tolist()
lista

[1, 2, 3]

In [ ]:
# ejercicio 18
l = [1, 2, 3]
a = np.array(l)
a

array([1, 2, 3])

In [ ]:
# ejercicio 19
m = np.array([[1, 2], [3, 4]])
pares = (m % 2 == 0)
pares

array([[False,  True],
       [False,  True]])

In [ ]:
# ejercicio 20
m = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m.shape

print("Filas:", filas)
print("Columnas:", columnas)

Filas: 2
Columnas: 3
